--
-- ============================================================
-- ALL SEQUENCES — Auto-Increment Sequences
-- ============================================================
--

-- SEQUENCE: auth_group_id_seq
ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- SEQUENCE: auth_group_permissions_id_seq
ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- SEQUENCE: auth_permission_id_seq
ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- SEQUENCE: auth_user_groups_id_seq
ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- SEQUENCE: auth_user_id_seq
ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- SEQUENCE: auth_user_user_permissions_id_seq
ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- SEQUENCE: chartofaccounts_account_id_seq
CREATE SEQUENCE public.chartofaccounts_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.chartofaccounts_account_id_seq OWNER TO postgres;

-- SEQUENCE OWNED BY: chartofaccounts_account_id_seq
ALTER SEQUENCE public.chartofaccounts_account_id_seq OWNED BY public.chartofaccounts.account_id;

-- SEQUENCE: django_admin_log_id_seq
ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- SEQUENCE: django_content_type_id_seq
ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- SEQUENCE: django_migrations_id_seq
ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- SEQUENCE: items_item_id_seq
CREATE SEQUENCE public.items_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.items_item_id_seq OWNER TO postgres;

-- SEQUENCE OWNED BY: items_item_id_seq
ALTER SEQUENCE public.items_item_id_seq OWNED BY public.items.item_id;

-- SEQUENCE: journalentries_journal_id_seq
CREATE SEQUENCE public.journalentries_journal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.journalentries_journal_id_seq OWNER TO postgres;

-- SEQUENCE OWNED BY: journalentries_journal_id_seq
ALTER SEQUENCE public.journalentries_journal_id_seq OWNED BY public.journalentries.journal_id;

-- SEQUENCE: journallines_line_id_seq
CREATE SEQUENCE public.journallines_line_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.journallines_line_id_seq OWNER TO postgres;

-- SEQUENCE OWNED BY: journallines_line_id_seq
ALTER SEQUENCE public.journallines_line_id_seq OWNED BY public.journallines.line_id;

-- SEQUENCE: parties_party_id_seq
CREATE SEQUENCE public.parties_party_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.parties_party_id_seq OWNER TO postgres;

-- SEQUENCE OWNED BY: parties_party_id_seq
ALTER SEQUENCE public.parties_party_id_seq OWNED BY public.parties.party_id;

-- SEQUENCE: payments_payment_id_seq
CREATE SEQUENCE public.payments_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.payments_payment_id_seq OWNER TO postgres;

-- SEQUENCE OWNED BY: payments_payment_id_seq
ALTER SEQUENCE public.payments_payment_id_seq OWNED BY public.payments.payment_id;

-- SEQUENCE: payments_ref_seq
CREATE SEQUENCE public.payments_ref_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.payments_ref_seq OWNER TO postgres;

-- SEQUENCE: purchaseinvoices_purchase_invoice_id_seq
CREATE SEQUENCE public.purchaseinvoices_purchase_invoice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.purchaseinvoices_purchase_invoice_id_seq OWNER TO postgres;

-- SEQUENCE OWNED BY: purchaseinvoices_purchase_invoice_id_seq
ALTER SEQUENCE public.purchaseinvoices_purchase_invoice_id_seq OWNED BY public.purchaseinvoices.purchase_invoice_id;

-- SEQUENCE: purchaseitems_purchase_item_id_seq
CREATE SEQUENCE public.purchaseitems_purchase_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.purchaseitems_purchase_item_id_seq OWNER TO postgres;

-- SEQUENCE OWNED BY: purchaseitems_purchase_item_id_seq
ALTER SEQUENCE public.purchaseitems_purchase_item_id_seq OWNED BY public.purchaseitems.purchase_item_id;

-- SEQUENCE: purchasereturnitems_return_item_id_seq
CREATE SEQUENCE public.purchasereturnitems_return_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.purchasereturnitems_return_item_id_seq OWNER TO postgres;

-- SEQUENCE OWNED BY: purchasereturnitems_return_item_id_seq
ALTER SEQUENCE public.purchasereturnitems_return_item_id_seq OWNED BY public.purchasereturnitems.return_item_id;

-- SEQUENCE: purchasereturns_purchase_return_id_seq
CREATE SEQUENCE public.purchasereturns_purchase_return_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.purchasereturns_purchase_return_id_seq OWNER TO postgres;

-- SEQUENCE OWNED BY: purchasereturns_purchase_return_id_seq
ALTER SEQUENCE public.purchasereturns_purchase_return_id_seq OWNED BY public.purchasereturns.purchase_return_id;

-- SEQUENCE: purchaseunits_unit_id_seq
CREATE SEQUENCE public.purchaseunits_unit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.purchaseunits_unit_id_seq OWNER TO postgres;

-- SEQUENCE OWNED BY: purchaseunits_unit_id_seq
ALTER SEQUENCE public.purchaseunits_unit_id_seq OWNED BY public.purchaseunits.unit_id;

-- SEQUENCE: receipts_receipt_id_seq
CREATE SEQUENCE public.receipts_receipt_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.receipts_receipt_id_seq OWNER TO postgres;

-- SEQUENCE OWNED BY: receipts_receipt_id_seq
ALTER SEQUENCE public.receipts_receipt_id_seq OWNED BY public.receipts.receipt_id;

-- SEQUENCE: receipts_ref_seq
CREATE SEQUENCE public.receipts_ref_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.receipts_ref_seq OWNER TO postgres;

-- SEQUENCE: salesinvoices_sales_invoice_id_seq
CREATE SEQUENCE public.salesinvoices_sales_invoice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.salesinvoices_sales_invoice_id_seq OWNER TO postgres;

-- SEQUENCE OWNED BY: salesinvoices_sales_invoice_id_seq
ALTER SEQUENCE public.salesinvoices_sales_invoice_id_seq OWNED BY public.salesinvoices.sales_invoice_id;

-- SEQUENCE: salesitems_sales_item_id_seq
CREATE SEQUENCE public.salesitems_sales_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.salesitems_sales_item_id_seq OWNER TO postgres;

-- SEQUENCE OWNED BY: salesitems_sales_item_id_seq
ALTER SEQUENCE public.salesitems_sales_item_id_seq OWNED BY public.salesitems.sales_item_id;

-- SEQUENCE: salesreturnitems_return_item_id_seq
CREATE SEQUENCE public.salesreturnitems_return_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.salesreturnitems_return_item_id_seq OWNER TO postgres;

-- SEQUENCE OWNED BY: salesreturnitems_return_item_id_seq
ALTER SEQUENCE public.salesreturnitems_return_item_id_seq OWNED BY public.salesreturnitems.return_item_id;

-- SEQUENCE: salesreturns_sales_return_id_seq
CREATE SEQUENCE public.salesreturns_sales_return_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.salesreturns_sales_return_id_seq OWNER TO postgres;

-- SEQUENCE OWNED BY: salesreturns_sales_return_id_seq
ALTER SEQUENCE public.salesreturns_sales_return_id_seq OWNED BY public.salesreturns.sales_return_id;

-- SEQUENCE: soldunits_sold_unit_id_seq
CREATE SEQUENCE public.soldunits_sold_unit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.soldunits_sold_unit_id_seq OWNER TO postgres;

-- SEQUENCE OWNED BY: soldunits_sold_unit_id_seq
ALTER SEQUENCE public.soldunits_sold_unit_id_seq OWNED BY public.soldunits.sold_unit_id;

-- SEQUENCE: stockmovements_movement_id_seq
CREATE SEQUENCE public.stockmovements_movement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.stockmovements_movement_id_seq OWNER TO postgres;

-- SEQUENCE OWNED BY: stockmovements_movement_id_seq
ALTER SEQUENCE public.stockmovements_movement_id_seq OWNED BY public.stockmovements.movement_id;
