--===============================================================================================
--                                       TABLES CREATED BY DJANGO START
--===============================================================================================


CREATE TABLE IF NOT EXISTS public.auth_group
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.auth_group_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.auth_permission
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename)
);

CREATE TABLE IF NOT EXISTS public.django_content_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    app_label character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id),
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
);

CREATE TABLE IF NOT EXISTS public.django_admin_log
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    action_time timestamp with time zone NOT NULL,
    object_id text COLLATE pg_catalog."default",
    object_repr character varying(200) COLLATE pg_catalog."default" NOT NULL,
    action_flag smallint NOT NULL,
    change_message text COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_session
(
    session_key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    session_data text COLLATE pg_catalog."default" NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);



CREATE TABLE IF NOT EXISTS public.django_migrations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    app character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS public.auth_user
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    CONSTRAINT auth_user_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.auth_user_groups
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id)
);

CREATE TABLE IF NOT EXISTS public.auth_user_user_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id)
);

ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e
    ON public.auth_group_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9
    ON public.auth_group_permissions(group_id);


ALTER TABLE IF EXISTS public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b
    ON public.auth_permission(content_type_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb
    ON public.django_admin_log(content_type_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_user_id_c564eba6
    ON public.django_admin_log(user_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_group_id_97559544
    ON public.auth_user_groups(group_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_user_id_6a12ed8b
    ON public.auth_user_groups(user_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_permission_id_1fbb5f2c
    ON public.auth_user_user_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_user_id_a95ead1b
    ON public.auth_user_user_permissions(user_id);

END;
--===============================================================================================
--                                       TABLES CREATED BY DJANGO END
--===============================================================================================

--===============================================================================================
--                                       TABLES CREATED CUSTOM START
--===============================================================================================

-- ======================================================
-- Chart of Accounts (COA)
-- ======================================================
CREATE TABLE ChartOfAccounts (
    account_id BIGSERIAL PRIMARY KEY,
    account_code VARCHAR(20) UNIQUE NOT NULL,
    account_name VARCHAR(150) NOT NULL,
    account_type VARCHAR(20) NOT NULL CHECK (account_type IN ('Asset','Liability','Equity','Revenue','Expense')),
    parent_account BIGINT REFERENCES ChartOfAccounts(account_id) ON DELETE SET NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



-- ======================================================
-- Parties (Customers, Vendors, Expenses)
-- ======================================================
CREATE TABLE Parties (
    party_id BIGSERIAL PRIMARY KEY,
    party_name VARCHAR(150) NOT NULL,
    party_type VARCHAR(20) NOT NULL CHECK (party_type IN ('Customer','Vendor','Both','Expense')),
    contact_info VARCHAR(50),
    address TEXT,

    ar_account_id BIGINT REFERENCES ChartOfAccounts(account_id) ON DELETE SET NULL,   -- linked ledger account (AR)

    ap_account_id BIGINT REFERENCES ChartOfAccounts(account_id) ON DELETE SET NULL,   -- linked ledger account (AP)

    opening_balance NUMERIC(14,2) DEFAULT 0,
    balance_type VARCHAR(10) CHECK (balance_type IN ('Debit','Credit')) DEFAULT 'Debit',

    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT unique_party_name UNIQUE (party_name)
);


-- ======================================================
-- Items (Products stored in inventory)
-- ======================================================
CREATE TABLE Items (
    item_id BIGSERIAL PRIMARY KEY,
    item_name VARCHAR(150) NOT NULL UNIQUE,
    storage VARCHAR(100),             -- Storage / warehouse
    sale_price NUMERIC(12,2) NOT NULL DEFAULT 0.00,          -- Default sale price
    item_code VARCHAR(50) UNIQUE,
    category VARCHAR(100),
    brand VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ======================================================
-- Journal Entries (Header)
-- ======================================================
CREATE TABLE JournalEntries (
    journal_id BIGSERIAL PRIMARY KEY,
    entry_date DATE NOT NULL DEFAULT CURRENT_DATE,
    description TEXT,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ======================================================
-- Journal Lines (Double-entry details)
-- ======================================================
CREATE TABLE JournalLines (
    line_id BIGSERIAL PRIMARY KEY,
    journal_id BIGINT NOT NULL REFERENCES JournalEntries(journal_id) ON DELETE CASCADE,
    account_id BIGINT NOT NULL REFERENCES ChartOfAccounts(account_id),
    party_id BIGINT REFERENCES Parties(party_id) ON DELETE SET NULL,
    debit NUMERIC(14,2) DEFAULT 0,
    credit NUMERIC(14,2) DEFAULT 0,
    CHECK (debit >= 0 AND credit >= 0),
    CHECK (NOT (debit = 0 AND credit = 0))
);


-- ======================================================
--             StockMovements (IN and OUT)
-- ======================================================
CREATE TABLE StockMovements (
    movement_id BIGSERIAL PRIMARY KEY,
    item_id BIGINT NOT NULL REFERENCES Items(item_id),
    serial_number TEXT,
    movement_type VARCHAR(20) NOT NULL CHECK (movement_type IN ('IN','OUT')),
    reference_type VARCHAR(50),   -- e.g., 'PurchaseInvoice'
    reference_id BIGINT,          -- purchase_invoice_id
    movement_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    quantity INT NOT NULL
);


-- ======================================================
-- Purchase Invoices (Header)
-- ======================================================
CREATE TABLE PurchaseInvoices (
    purchase_invoice_id BIGSERIAL PRIMARY KEY,
    vendor_id BIGINT NOT NULL REFERENCES Parties(party_id) ON DELETE CASCADE,
    invoice_date DATE NOT NULL DEFAULT CURRENT_DATE,
    total_amount NUMERIC(14,2) NOT NULL,
    journal_id BIGINT REFERENCES JournalEntries(journal_id) ON DELETE SET NULL
);


-- ======================================================
-- Purchase Items (Line items)
-- ======================================================
CREATE TABLE PurchaseItems (
    purchase_item_id BIGSERIAL PRIMARY KEY,
    purchase_invoice_id BIGINT NOT NULL REFERENCES PurchaseInvoices(purchase_invoice_id) ON DELETE CASCADE,
    item_id BIGINT NOT NULL REFERENCES Items(item_id),
    quantity INT NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(12,2) NOT NULL
);


-- ======================================================
-- Purchase Units (Serial numbers for purchased items)
-- ======================================================
CREATE TABLE PurchaseUnits (
    unit_id BIGSERIAL PRIMARY KEY,
    purchase_item_id BIGINT NOT NULL REFERENCES PurchaseItems(purchase_item_id) ON DELETE CASCADE,
    serial_number VARCHAR(100) UNIQUE NOT NULL,
    in_stock BOOLEAN DEFAULT TRUE
);

-- ============================================================
-- MIGRATION: Add serial_comment to PurchaseUnits
-- Date: 2026-02-07
-- Purpose: Allow optional comments for individual serial numbers
-- ============================================================

BEGIN;

-- Add the serial_comment column to PurchaseUnits table
ALTER TABLE PurchaseUnits 
ADD COLUMN IF NOT EXISTS serial_comment TEXT NULL;

-- Add column documentation
COMMENT ON COLUMN PurchaseUnits.serial_comment IS 
'Optional comment for this serial number (informational only, does not affect accounting, inventory valuation, or ledger postings)';


-- ======================================================
-- Sales Invoices (Header)
-- ======================================================
CREATE TABLE SalesInvoices (
    sales_invoice_id BIGSERIAL PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES Parties(party_id) ON DELETE CASCADE,
    invoice_date DATE NOT NULL DEFAULT CURRENT_DATE,
    total_amount NUMERIC(14,2) NOT NULL,
    journal_id BIGINT REFERENCES JournalEntries(journal_id) ON DELETE SET NULL
);

-- ======================================================
-- Sales Items (Line items)
-- ======================================================
CREATE TABLE SalesItems (
    sales_item_id BIGSERIAL PRIMARY KEY,
    sales_invoice_id BIGINT NOT NULL REFERENCES SalesInvoices(sales_invoice_id) ON DELETE CASCADE,
    item_id BIGINT NOT NULL REFERENCES Items(item_id),
    quantity INT NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(12,2) NOT NULL
);

-- ======================================================
-- Sold Units (Serial numbers for sold items)
-- ======================================================
CREATE TABLE SoldUnits (
    sold_unit_id BIGSERIAL PRIMARY KEY,
    sales_item_id BIGINT NOT NULL REFERENCES SalesItems(sales_item_id) ON DELETE CASCADE,
    unit_id BIGINT NOT NULL REFERENCES PurchaseUnits(unit_id) ON DELETE CASCADE,
    sold_price NUMERIC(12,2) NOT NULL,
    status VARCHAR(20) DEFAULT 'Sold' CHECK (status IN ('Sold','Returned','Damaged'))
    
);


-- ======================================================
-- Payments (Outgoing to vendors)
-- ======================================================
CREATE TABLE Payments (
    payment_id BIGSERIAL PRIMARY KEY,
    party_id BIGINT NOT NULL REFERENCES Parties(party_id) ON DELETE CASCADE,
    account_id BIGINT NOT NULL REFERENCES ChartOfAccounts(account_id),
    amount NUMERIC(14,2) NOT NULL CHECK (amount > 0),
    payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
    method VARCHAR(20) CHECK (method IN ('Cash','Bank','Cheque','Online')),
    reference_no VARCHAR(100),
    journal_id BIGINT REFERENCES JournalEntries(journal_id) ON DELETE SET NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    notes TEXT,
	description TEXT
);

ALTER TABLE Payments
ALTER COLUMN amount TYPE NUMERIC(14,4);

-- ======================================================
-- Receipts (Incoming from customers)
-- ======================================================
CREATE TABLE Receipts (
    receipt_id BIGSERIAL PRIMARY KEY,
    party_id BIGINT NOT NULL REFERENCES Parties(party_id) ON DELETE CASCADE,
    account_id BIGINT NOT NULL REFERENCES ChartOfAccounts(account_id),
    amount NUMERIC(14,2) NOT NULL CHECK (amount > 0),
    receipt_date DATE NOT NULL DEFAULT CURRENT_DATE,
    method VARCHAR(20) CHECK (method IN ('Cash','Bank','Cheque','Online')),
    reference_no VARCHAR(100),
    journal_id BIGINT REFERENCES JournalEntries(journal_id) ON DELETE SET NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    notes TEXT,
	description TEXT
);

ALTER TABLE Receipts
ALTER COLUMN amount TYPE NUMERIC(14,4);

-- ======================================================
-- Purchase Returns (Header)
-- ======================================================
CREATE TABLE PurchaseReturns (
    purchase_return_id BIGSERIAL PRIMARY KEY,
    vendor_id BIGINT NOT NULL REFERENCES Parties(party_id) ON DELETE CASCADE,
    return_date DATE NOT NULL DEFAULT CURRENT_DATE,
    total_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    journal_id BIGINT REFERENCES JournalEntries(journal_id) ON DELETE SET NULL
);

-- Line items (with serials)
CREATE TABLE PurchaseReturnItems (
    return_item_id BIGSERIAL PRIMARY KEY,
    purchase_return_id BIGINT NOT NULL REFERENCES PurchaseReturns(purchase_return_id) ON DELETE CASCADE,
    item_id BIGINT NOT NULL REFERENCES Items(item_id),
    unit_price NUMERIC(12,2) NOT NULL,
    serial_number VARCHAR(100) NOT NULL
);

-- ======================================================
-- Sales Returns (Header)
-- ======================================================
CREATE TABLE SalesReturns (
    sales_return_id BIGSERIAL PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES Parties(party_id) ON DELETE CASCADE,
    return_date DATE NOT NULL DEFAULT CURRENT_DATE,
    total_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    journal_id BIGINT REFERENCES JournalEntries(journal_id) ON DELETE SET NULL
);

-- Line items (with serials)
CREATE TABLE SalesReturnItems (
    return_item_id BIGSERIAL PRIMARY KEY,
    sales_return_id BIGINT NOT NULL REFERENCES SalesReturns(sales_return_id) ON DELETE CASCADE,
    item_id BIGINT NOT NULL REFERENCES Items(item_id),
    sold_price NUMERIC(12,2) NOT NULL,
    cost_price NUMERIC(12,2) NOT NULL,
    serial_number VARCHAR(100) NOT NULL
);



--===============================================================================================
--                                       TABLES END
--===============================================================================================
