-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.auth_group
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.auth_group_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.auth_permission
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename)
);

CREATE TABLE IF NOT EXISTS public.auth_user
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    CONSTRAINT auth_user_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.auth_user_groups
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id)
);

CREATE TABLE IF NOT EXISTS public.auth_user_user_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.chartofaccounts
(
    account_id bigserial NOT NULL,
    account_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    account_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    account_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    parent_account bigint,
    date_created timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chartofaccounts_pkey PRIMARY KEY (account_id),
    CONSTRAINT chartofaccounts_account_code_key UNIQUE (account_code)
);

CREATE TABLE IF NOT EXISTS public.django_admin_log
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    action_time timestamp with time zone NOT NULL,
    object_id text COLLATE pg_catalog."default",
    object_repr character varying(200) COLLATE pg_catalog."default" NOT NULL,
    action_flag smallint NOT NULL,
    change_message text COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_content_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    app_label character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id),
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
);

CREATE TABLE IF NOT EXISTS public.django_migrations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    app character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_session
(
    session_key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    session_data text COLLATE pg_catalog."default" NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);

CREATE TABLE IF NOT EXISTS public.items
(
    item_id bigserial NOT NULL,
    item_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    storage character varying(100) COLLATE pg_catalog."default",
    sale_price numeric(12, 2) NOT NULL DEFAULT 0.00,
    item_code character varying(50) COLLATE pg_catalog."default",
    category character varying(100) COLLATE pg_catalog."default",
    brand character varying(100) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT items_pkey PRIMARY KEY (item_id),
    CONSTRAINT items_item_code_key UNIQUE (item_code),
    CONSTRAINT items_item_name_key UNIQUE (item_name)
);

CREATE TABLE IF NOT EXISTS public.journalentries
(
    journal_id bigserial NOT NULL,
    entry_date date NOT NULL DEFAULT CURRENT_DATE,
    description text COLLATE pg_catalog."default",
    date_created timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT journalentries_pkey PRIMARY KEY (journal_id)
);

CREATE TABLE IF NOT EXISTS public.journallines
(
    line_id bigserial NOT NULL,
    journal_id bigint NOT NULL,
    account_id bigint NOT NULL,
    party_id bigint,
    debit numeric(14, 2) DEFAULT 0,
    credit numeric(14, 2) DEFAULT 0,
    CONSTRAINT journallines_pkey PRIMARY KEY (line_id)
);

CREATE TABLE IF NOT EXISTS public.parties
(
    party_id bigserial NOT NULL,
    party_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    party_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    contact_info character varying(50) COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    ar_account_id bigint,
    ap_account_id bigint,
    opening_balance numeric(14, 2) DEFAULT 0,
    balance_type character varying(10) COLLATE pg_catalog."default" DEFAULT 'Debit'::character varying,
    date_created timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT parties_pkey PRIMARY KEY (party_id),
    CONSTRAINT unique_party_name UNIQUE (party_name)
);

CREATE TABLE IF NOT EXISTS public.payments
(
    payment_id bigserial NOT NULL,
    party_id bigint NOT NULL,
    account_id bigint NOT NULL,
    amount numeric(14, 4) NOT NULL,
    payment_date date NOT NULL DEFAULT CURRENT_DATE,
    method character varying(20) COLLATE pg_catalog."default",
    reference_no character varying(100) COLLATE pg_catalog."default",
    journal_id bigint,
    date_created timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    notes text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    CONSTRAINT payments_pkey PRIMARY KEY (payment_id)
);

CREATE TABLE IF NOT EXISTS public.purchaseinvoices
(
    purchase_invoice_id bigserial NOT NULL,
    vendor_id bigint NOT NULL,
    invoice_date date NOT NULL DEFAULT CURRENT_DATE,
    total_amount numeric(14, 2) NOT NULL,
    journal_id bigint,
    CONSTRAINT purchaseinvoices_pkey PRIMARY KEY (purchase_invoice_id)
);

CREATE TABLE IF NOT EXISTS public.purchaseitems
(
    purchase_item_id bigserial NOT NULL,
    purchase_invoice_id bigint NOT NULL,
    item_id bigint NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(12, 2) NOT NULL,
    CONSTRAINT purchaseitems_pkey PRIMARY KEY (purchase_item_id)
);

CREATE TABLE IF NOT EXISTS public.purchasereturnitems
(
    return_item_id bigserial NOT NULL,
    purchase_return_id bigint NOT NULL,
    item_id bigint NOT NULL,
    unit_price numeric(12, 2) NOT NULL,
    serial_number character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT purchasereturnitems_pkey PRIMARY KEY (return_item_id)
);

CREATE TABLE IF NOT EXISTS public.purchasereturns
(
    purchase_return_id bigserial NOT NULL,
    vendor_id bigint NOT NULL,
    return_date date NOT NULL DEFAULT CURRENT_DATE,
    total_amount numeric(14, 2) NOT NULL DEFAULT 0,
    journal_id bigint,
    CONSTRAINT purchasereturns_pkey PRIMARY KEY (purchase_return_id)
);

CREATE TABLE IF NOT EXISTS public.purchaseunits
(
    unit_id bigserial NOT NULL,
    purchase_item_id bigint NOT NULL,
    serial_number character varying(100) COLLATE pg_catalog."default" NOT NULL,
    in_stock boolean DEFAULT true,
    serial_comment text COLLATE pg_catalog."default",
    CONSTRAINT purchaseunits_pkey PRIMARY KEY (unit_id),
    CONSTRAINT purchaseunits_serial_number_key UNIQUE (serial_number)
);

COMMENT ON COLUMN public.purchaseunits.serial_comment
    IS 'Optional comment for this serial number (informational only, does not affect accounting, inventory valuation, or ledger postings)';

CREATE TABLE IF NOT EXISTS public.receipts
(
    receipt_id bigserial NOT NULL,
    party_id bigint NOT NULL,
    account_id bigint NOT NULL,
    amount numeric(14, 4) NOT NULL,
    receipt_date date NOT NULL DEFAULT CURRENT_DATE,
    method character varying(20) COLLATE pg_catalog."default",
    reference_no character varying(100) COLLATE pg_catalog."default",
    journal_id bigint,
    date_created timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    notes text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    CONSTRAINT receipts_pkey PRIMARY KEY (receipt_id)
);

CREATE TABLE IF NOT EXISTS public.salesinvoices
(
    sales_invoice_id bigserial NOT NULL,
    customer_id bigint NOT NULL,
    invoice_date date NOT NULL DEFAULT CURRENT_DATE,
    total_amount numeric(14, 2) NOT NULL,
    journal_id bigint,
    CONSTRAINT salesinvoices_pkey PRIMARY KEY (sales_invoice_id)
);

CREATE TABLE IF NOT EXISTS public.salesitems
(
    sales_item_id bigserial NOT NULL,
    sales_invoice_id bigint NOT NULL,
    item_id bigint NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(12, 2) NOT NULL,
    CONSTRAINT salesitems_pkey PRIMARY KEY (sales_item_id)
);

CREATE TABLE IF NOT EXISTS public.salesreturnitems
(
    return_item_id bigserial NOT NULL,
    sales_return_id bigint NOT NULL,
    item_id bigint NOT NULL,
    sold_price numeric(12, 2) NOT NULL,
    cost_price numeric(12, 2) NOT NULL,
    serial_number character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT salesreturnitems_pkey PRIMARY KEY (return_item_id)
);

CREATE TABLE IF NOT EXISTS public.salesreturns
(
    sales_return_id bigserial NOT NULL,
    customer_id bigint NOT NULL,
    return_date date NOT NULL DEFAULT CURRENT_DATE,
    total_amount numeric(14, 2) NOT NULL DEFAULT 0,
    journal_id bigint,
    CONSTRAINT salesreturns_pkey PRIMARY KEY (sales_return_id)
);

CREATE TABLE IF NOT EXISTS public.soldunits
(
    sold_unit_id bigserial NOT NULL,
    sales_item_id bigint NOT NULL,
    unit_id bigint NOT NULL,
    sold_price numeric(12, 2) NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'Sold'::character varying,
    CONSTRAINT soldunits_pkey PRIMARY KEY (sold_unit_id)
);

CREATE TABLE IF NOT EXISTS public.stockmovements
(
    movement_id bigserial NOT NULL,
    item_id bigint NOT NULL,
    serial_number text COLLATE pg_catalog."default",
    movement_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    reference_type character varying(50) COLLATE pg_catalog."default",
    reference_id bigint,
    movement_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    quantity integer NOT NULL,
    CONSTRAINT stockmovements_pkey PRIMARY KEY (movement_id)
);

ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e
    ON public.auth_group_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9
    ON public.auth_group_permissions(group_id);


ALTER TABLE IF EXISTS public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b
    ON public.auth_permission(content_type_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_group_id_97559544
    ON public.auth_user_groups(group_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_user_id_6a12ed8b
    ON public.auth_user_groups(user_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_permission_id_1fbb5f2c
    ON public.auth_user_user_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_user_id_a95ead1b
    ON public.auth_user_user_permissions(user_id);


ALTER TABLE IF EXISTS public.chartofaccounts
    ADD CONSTRAINT chartofaccounts_parent_account_fkey FOREIGN KEY (parent_account)
    REFERENCES public.chartofaccounts (account_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb
    ON public.django_admin_log(content_type_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_user_id_c564eba6
    ON public.django_admin_log(user_id);


ALTER TABLE IF EXISTS public.journallines
    ADD CONSTRAINT journallines_account_id_fkey FOREIGN KEY (account_id)
    REFERENCES public.chartofaccounts (account_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.journallines
    ADD CONSTRAINT journallines_journal_id_fkey FOREIGN KEY (journal_id)
    REFERENCES public.journalentries (journal_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.journallines
    ADD CONSTRAINT journallines_party_id_fkey FOREIGN KEY (party_id)
    REFERENCES public.parties (party_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.parties
    ADD CONSTRAINT parties_ap_account_id_fkey FOREIGN KEY (ap_account_id)
    REFERENCES public.chartofaccounts (account_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.parties
    ADD CONSTRAINT parties_ar_account_id_fkey FOREIGN KEY (ar_account_id)
    REFERENCES public.chartofaccounts (account_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT payments_account_id_fkey FOREIGN KEY (account_id)
    REFERENCES public.chartofaccounts (account_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT payments_journal_id_fkey FOREIGN KEY (journal_id)
    REFERENCES public.journalentries (journal_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT payments_party_id_fkey FOREIGN KEY (party_id)
    REFERENCES public.parties (party_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.purchaseinvoices
    ADD CONSTRAINT purchaseinvoices_journal_id_fkey FOREIGN KEY (journal_id)
    REFERENCES public.journalentries (journal_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.purchaseinvoices
    ADD CONSTRAINT purchaseinvoices_vendor_id_fkey FOREIGN KEY (vendor_id)
    REFERENCES public.parties (party_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.purchaseitems
    ADD CONSTRAINT purchaseitems_item_id_fkey FOREIGN KEY (item_id)
    REFERENCES public.items (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.purchaseitems
    ADD CONSTRAINT purchaseitems_purchase_invoice_id_fkey FOREIGN KEY (purchase_invoice_id)
    REFERENCES public.purchaseinvoices (purchase_invoice_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.purchasereturnitems
    ADD CONSTRAINT purchasereturnitems_item_id_fkey FOREIGN KEY (item_id)
    REFERENCES public.items (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.purchasereturnitems
    ADD CONSTRAINT purchasereturnitems_purchase_return_id_fkey FOREIGN KEY (purchase_return_id)
    REFERENCES public.purchasereturns (purchase_return_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.purchasereturns
    ADD CONSTRAINT purchasereturns_journal_id_fkey FOREIGN KEY (journal_id)
    REFERENCES public.journalentries (journal_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.purchasereturns
    ADD CONSTRAINT purchasereturns_vendor_id_fkey FOREIGN KEY (vendor_id)
    REFERENCES public.parties (party_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.purchaseunits
    ADD CONSTRAINT purchaseunits_purchase_item_id_fkey FOREIGN KEY (purchase_item_id)
    REFERENCES public.purchaseitems (purchase_item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.receipts
    ADD CONSTRAINT receipts_account_id_fkey FOREIGN KEY (account_id)
    REFERENCES public.chartofaccounts (account_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.receipts
    ADD CONSTRAINT receipts_journal_id_fkey FOREIGN KEY (journal_id)
    REFERENCES public.journalentries (journal_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.receipts
    ADD CONSTRAINT receipts_party_id_fkey FOREIGN KEY (party_id)
    REFERENCES public.parties (party_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.salesinvoices
    ADD CONSTRAINT salesinvoices_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.parties (party_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.salesinvoices
    ADD CONSTRAINT salesinvoices_journal_id_fkey FOREIGN KEY (journal_id)
    REFERENCES public.journalentries (journal_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.salesitems
    ADD CONSTRAINT salesitems_item_id_fkey FOREIGN KEY (item_id)
    REFERENCES public.items (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.salesitems
    ADD CONSTRAINT salesitems_sales_invoice_id_fkey FOREIGN KEY (sales_invoice_id)
    REFERENCES public.salesinvoices (sales_invoice_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.salesreturnitems
    ADD CONSTRAINT salesreturnitems_item_id_fkey FOREIGN KEY (item_id)
    REFERENCES public.items (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.salesreturnitems
    ADD CONSTRAINT salesreturnitems_sales_return_id_fkey FOREIGN KEY (sales_return_id)
    REFERENCES public.salesreturns (sales_return_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.salesreturns
    ADD CONSTRAINT salesreturns_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.parties (party_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.salesreturns
    ADD CONSTRAINT salesreturns_journal_id_fkey FOREIGN KEY (journal_id)
    REFERENCES public.journalentries (journal_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.soldunits
    ADD CONSTRAINT soldunits_sales_item_id_fkey FOREIGN KEY (sales_item_id)
    REFERENCES public.salesitems (sales_item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.soldunits
    ADD CONSTRAINT soldunits_unit_id_fkey FOREIGN KEY (unit_id)
    REFERENCES public.purchaseunits (unit_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.stockmovements
    ADD CONSTRAINT stockmovements_item_id_fkey FOREIGN KEY (item_id)
    REFERENCES public.items (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;